version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

